### ISSUE TITLE
java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libnio.so: /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0: file too short

### ISSUE THREAD

**Issue by edouardpoitras** [dwmkerr/docker-dynamodb#8]
Getting the above error when trying to run the latest image: 
```
─> docker run -p 8000:8000 dwmkerr/dynamodb:latest
Initializing DynamoDB Local with the following configuration:
Port:	8000
InMemory:	false
DbPath:	null
SharedDb:	false
shouldDelayTransientStatuses:	false
CorsParams:	*

ERROR StatusLogger Error creating converter for d
 java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.logging.log4j.core.pattern.PatternParser.createConverter(PatternParser.java:549)
	at org.apache.logging.log4j.core.pattern.PatternParser.finalizeConverter(PatternParser.java:602)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:386)
	at org.apache.logging.log4j.core.pattern.PatternParser.parse(PatternParser.java:171)
	at org.apache.logging.log4j.core.layout.PatternLayout.createSerializer(PatternLayout.java:124)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:111)
	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:58)
	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:494)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:551)
	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:74)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:171)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:70)
	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:147)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
	at com.amazonaws.services.dynamodbv2.local.shared.logging.LogManager.getLogger(LogManager.java:49)
	at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.<clinit>(DynamoDBProxyServer.java:36)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServer(ServerRunner.java:124)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServerFromCommandLineArgs(ServerRunner.java:120)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.main(ServerRunner.java:71)
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libnio.so: /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0: file too short
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1968)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1893)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:561)
	at sun.nio.fs.UnixNativeDispatcher$1.run(UnixNativeDispatcher.java:559)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.fs.UnixNativeDispatcher.<clinit>(UnixNativeDispatcher.java:559)
	at sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:67)
	at sun.nio.fs.LinuxFileSystem.<init>(LinuxFileSystem.java:39)
	at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:44)
	at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:37)
	at sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:56)
	at sun.nio.fs.LinuxFileSystemProvider.<init>(LinuxFileSystemProvider.java:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at sun.nio.fs.DefaultFileSystemProvider$1.run(DefaultFileSystemProvider.java:52)
	at sun.nio.fs.DefaultFileSystemProvider$1.run(DefaultFileSystemProvider.java:43)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:42)
	at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:70)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.getDefaultProvider(FileSystems.java:108)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.access$000(FileSystems.java:89)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:98)
	at java.nio.file.FileSystems$DefaultFileSystemHolder$1.run(FileSystems.java:96)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.defaultFileSystem(FileSystems.java:95)
	at java.nio.file.FileSystems$DefaultFileSystemHolder.<clinit>(FileSystems.java:90)
	at java.nio.file.FileSystems.getDefault(FileSystems.java:176)
	at sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:490)
	at sun.util.calendar.ZoneInfoFile$1.run(ZoneInfoFile.java:481)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.util.calendar.ZoneInfoFile.<clinit>(ZoneInfoFile.java:480)
	at sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:663)
	at java.util.TimeZone.getTimeZone(TimeZone.java:566)
	at java.util.TimeZone.setDefaultZone(TimeZone.java:663)
	at java.util.TimeZone.getDefaultRef(TimeZone.java:630)
	at java.util.Calendar.getInstance(Calendar.java:968)
	at org.apache.logging.log4j.core.util.datetime.FixedDateFormat.calcMidnightMillis(FixedDateFormat.java:247)
	at org.apache.logging.log4j.core.util.datetime.FixedDateFormat.updateMidnightMillis(FixedDateFormat.java:242)
	at org.apache.logging.log4j.core.util.datetime.FixedDateFormat.millisSinceMidnight(FixedDateFormat.java:233)
	at org.apache.logging.log4j.core.util.datetime.FixedDateFormat.format(FixedDateFormat.java:281)
	at org.apache.logging.log4j.core.util.datetime.FixedDateFormat.format(FixedDateFormat.java:269)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter$FixedFormatter.format(DatePatternConverter.java:94)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter$CachedTime.<init>(DatePatternConverter.java:143)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.<init>(DatePatternConverter.java:171)
	at org.apache.logging.log4j.core.pattern.DatePatternConverter.newInstance(DatePatternConverter.java:189)
	... 28 more
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/libnet.so: /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0: file too short
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1968)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1893)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.InetAddress.<clinit>(InetAddress.java:291)
	at org.apache.logging.log4j.core.util.NetUtils.getLocalHostname(NetUtils.java:53)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:490)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:566)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:582)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:217)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:551)
	at com.amazonaws.services.dynamodbv2.local.shared.logging.LogManager.getLogger(LogManager.java:49)
	at com.amazonaws.services.dynamodbv2.local.server.DynamoDBProxyServer.<clinit>(DynamoDBProxyServer.java:36)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServer(ServerRunner.java:124)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServerFromCommandLineArgs(ServerRunner.java:120)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.main(ServerRunner.java:71)
```

However, running image 38 works as expected:

```
─> docker run -p 8000:8000 dwmkerr/dynamodb:38
Initializing DynamoDB Local with the following configuration:
Port:	8000
InMemory:	false
DbPath:	null
SharedDb:	false
shouldDelayTransientStatuses:	false
CorsParams:	*
```

**Comment by dwmkerr** [comment]
Very strange, looking into this now!

**Comment by dwmkerr** [comment]
Would you mind trying again now @edouardpoitras? I've rebuilt the image, rerun the tests and redeployed (although I wasn't able to reproduce the issue)

**Comment by edouardpoitras** [comment]
That seems to have done the trick. Thanks!

**Comment by dwmkerr** [comment]
Great! Good news
